### PR TITLE
Add CVMFS_FALLBACK_PROXY to config-egi.egi.eu.conf

### PR DESCRIPTION
**Pull request by DrDaveD**

### CODE REVIEW

**Comment by DrDaveD** [comment]
Also please tag repo with '1.1-1'.  (I know that the cvmfs repo puts on the repo name as a prefix, but github download works better with just a revision number and in fact I refer to that URL as the source in the .spec file)

**Comment by jblomer** [comment]
You should have gotten an invitation as a team member for this repository so that you can make changes to the repository.

**Comment by DrDaveD** [comment]
Yes I did, so shall I push the tag myself?

**Comment by jblomer** [comment]
Yes, please go ahead.

**Comment by DrDaveD** [comment]
Ok, the tag is pushed.

**Pull request merged**
